Feat/search in elasticsearch
basedosdados/backend pull request #183
Opened 2023-05-25 16:43 UTC by mfagundes

2023-05-25 17:04 UTC, gabriel-milan requested changes

2023-05-25 17:04 UTC, gabriel-milan commented on basedosdados_api/api/v1/views.py
> +        es = Elasticsearch()
aqui deve ter alguma forma de informar a URL do ES, que está configurada nas envs

2023-05-25 17:04 UTC, gabriel-milan commented on basedosdados_api/api/v1/views.py
> +        self.queryset = es.search(index="default", body=raw_query)
mesma coisa com o index aqui, não deixar hardcoded, pega dos settings do django

2023-05-25 20:58 UTC, mfagundes commented on basedosdados_api/api/v1/views.py
> +        es = Elasticsearch()
Ela está nos settings do Django, puxei de lá.

2023-05-25 20:58 UTC, mfagundes commented on basedosdados_api/api/v1/views.py
> +        self.queryset = es.search(index="default", body=raw_query)
Feito, mas aqui ela está hardcoded, o ideal seria mudar para uma variável de ambiente nos settigns

2023-05-26 18:34 UTC, gabriel-milan approved these changes

2023-05-26 18:34 UTC, gabriel-milan approved these changes

2023-05-26 19:05 UTC, merged