fix: make license optional
basedosdados/backend pull request #363
Opened 2023-08-29 23:01 UTC by vncsna

### Purpose

### Description

### Checklist

- [ ] I have reviewed the code changes.
- [ ] I have tested the changes locally.
- [ ] I have updated the documentation if needed.
- [ ] I have added/modified tests to ensure the changes are valid.

### Testing and evidence

### Next steps

2023-08-29 23:09 UTC, mfagundes requested changes

2023-08-29 23:09 UTC, mfagundes commented on basedosdados_api/api/v1/models.py
> +        "License", on_delete=models.CASCADE, related_name="raw_data_sources", blank=True, null=True
Acho que, de fato, isso deveria estar em diversos modelos, não apenas no `RawDataSource`. Verifique isso, pois não localizei o PR original

2023-08-29 23:12 UTC, vncsna commented on basedosdados_api/api/v1/models.py
> +        "License", on_delete=models.CASCADE, related_name="raw_data_sources", blank=True, null=True
O [PR](https://github.com/basedosdados/backend/pull/333) original tem essa alteração em apenas um modelo

2023-08-30 00:07 UTC, rdahis commented on basedosdados_api/api/v1/models.py
> +        "License", on_delete=models.CASCADE, related_name="raw_data_sources", blank=True, null=True
Acho que é só aqui mesmo.

2023-08-30 21:57 UTC, merged

2023-08-30 22:22 UTC, rdahis commented
Foi direto pra `main` sem passar por `development` e `staging`?