feat: poll
basedosdados/backend pull request #622
Opened 2024-06-21 12:54 UTC by rdahis

2024-06-21 12:59 UTC, jhony-spocket requested changes
Faltou criar as migrations com o comando do Django.

Como você adicionou um novo modelo é necessário gerar as migrations com o django. Para isso é só rodar os seguintes commandos:

Esse vai gerar as migrations com base nas alterações dos modelos:
```bash
python manage.py makemigrations
```
Esse var aplicar as migrations no seu banco de dados local.
```bash
python manage.py migrate
```

2024-06-21 13:13 UTC, jhony-spocket commented on backend/apps/api/v1/models.py
> +    lag = models.IntegerField(blank=True, null=True)
O que seria esse lag?

2024-06-21 13:13 UTC, jhony-spocket commented on backend/apps/api/v1/models.py
> +            )
Remover essa lógica de count parar simplificar o código. Podemos usar um xor aqui com o "bool" e o "=="

```suggestion
        if  bool(self.raw_data_source) == bool(self.information_request):
            raise ValidationError(
                "One and only one of 'raw_data_source',"
                " or 'information_request' must be set."
            )
```

Se ambos os campos raw_data_source e information_request estiverem presentes no modelo, o erro será acionado. No entanto, se ambos estiverem ausentes, ou seja, se não houver nem raw_data_source nem information_request, um erro também será disparado. Agora, se um dos campos estiver presente e o outro não, nenhum erro será disparado.

2024-06-21 13:13 UTC, jhony-spocket commented on backend/apps/api/v1/models.py
> +        return max(polls) if polls else None
Não encontrei nehuma referência ao campo ``last_polled_at`` no projeto que no caso deveria está presente no modelo RawDataSource. Ele também não é atualizado/setado em nenhum lugar então essa lógica está quebrada acredito que seja necessário realizar a implementação que falta.

2024-06-21 13:17 UTC, rdahis commented on backend/apps/api/v1/models.py
> +    lag = models.IntegerField(blank=True, null=True)
De fato não faz sentido no `poll`. Boa.

2024-06-25 00:14 UTC, rdahis commented
@jhony-spocket acho que está faltando só rodar o `python manage.py makemigrations`. Não consegui rodar local por questão de ambiente. Caso consiga aí pode subir o commit e damos merge.

2024-06-26 11:18 UTC, jhonylucas74 commented
A migration foi criada.

2024-06-26 13:22 UTC, merged